In [1]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5]
