In [2]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [8]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5]


In [1]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [3]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
     

0
1
2
3
